# Data Scrape Testing

- Data sourced from Firecrawler. 
- Notebook explores 3 methods in using DataFrames to load the scraped text into table.

In [2]:
crawler_markdown = """# GET INTO THE MLB ACTION

- Post Button

- Facebook


- [Live Sports Odds](https://www.sportsbet.com/live-odds/)
- [Baseball Betting](https://www.sportsbet.com/live-odds/sport.html?id=Baseball)
- MLB Betting Odds

# MLB Betting Odds

We offer the latest MLB Betting Odds online. Check out up-to-the-minute point spreads, money lines and totals betting odds for your favorite MLB team now.

| DATE | MATCHUP | SPREAD | MONEY | TOTAL |
| --- | --- | --- | --- | --- |
| Tuesday,<br> Aug. 11,<br> 06:45 pm | Pittsburgh Pirates at | _(-1.5) +146_ | _-119_ | _(O: 7) -113_ |
| Miami Marlins | _(+1.5) -166_ | _+108_ | _(U: 7) -107_ |
| Tuesday,<br> Aug. 11,<br> 06:50 pm | Chicago Cubs at | _(-1.5) -105_ | _-163_ | _(O: 9) -104_ |
| Washington Nationals | _(+1.5) -115_ | _+147_ | _(U: 9) -116_ |
| Tuesday,<br> Aug. 11,<br> 07:20 pm | New York Mets at | _(+1.5) -185_ | _+113_ | _(O: 8) -125_ |
| Atlanta Braves | _(-1.5) +161_ | _-125_ | _(U: 8) +105_ |
| Tuesday,<br> Aug. 11,<br> 07:50 pm | Philadelphia Phillies at | _(-1.5) +103_ | _-160_ | _(O: 8) -115_ |
| St. Louis Cardinals | _(+1.5) -123_ | _+145_ | _(U: 8) -105_ |
| Tuesday,<br> Aug. 11,<br> 09:45 pm | Colorado Rockies at | _(+1.5) -133_ | _+157_ | _(O: 9) -125_ |
| Arizona Diamondbacks | _(-1.5) +113_ | _-174_ | _(U: 9) +105_ |
| Tuesday,<br> Aug. 11,<br> 09:45 pm | Milwaukee Brewers at | _(-1.5) +125_ | _-138_ | _(O: 8) +105_ |
| San Diego Padres | _(+1.5) -145_ | _+125_ | _(U: 8) -125_ |
| Tuesday,<br> Aug. 11,<br> 06:45 pm | Cleveland Guardians at | _(+1.5) -190_ | _+113_ | _(O: 8.5) -110_ |
| Detroit Tigers | _(-1.5) +165_ | _-125_ | _(U: 8.5) -110_ |
| Tuesday,<br> Aug. 11,<br> 07:10 pm | Seattle Mariners at | _(+1.5) -185_ | _+113_ | _(O: 8.5) +105_ |
| New York Yankees | _(-1.5) +161_ | _-125_ | _(U: 8.5) -125_ |
| Tuesday,<br> Aug. 11,<br> 07:12 pm | Boston Red Sox at | _(+1.5) -167_ | _+127_ | _(O: 7.5) +108_ |
| Toronto Blue Jays | _(-1.5) +147_ | _-140_ | _(U: 7.5) -128_ |
| Tuesday,<br> Aug. 11,<br> 07:45 pm | Baltimore Orioles at | _(+1.5) -195_ | _+104_ | _(O: 9.5) -105_ |
| Minnesota Twins | _(-1.5) +170_ | _-115_ | _(U: 9.5) -115_ |
| Tuesday,<br> Aug. 11,<br> 09:43 pm | Texas Rangers at | _(-1.5) +115_ | _-138_ | _(O: 9) -118_ |
| Los Angeles Angels | _(+1.5) -135_ | _+125_ | _(U: 9) -102_ |
| Tuesday,<br> Aug. 11,<br> 09:45 pm | Tampa Bay Rays at | _(-1.5) -102_ | _-158_ | _(O: 9.5) -126_ |
| Athletics | _(+1.5) -118_ | _+143_ | _(U: 9.5) +106_ |
| Tuesday,<br> Aug. 11,<br> 07:45 pm | Cincinnati Reds at | _(+1.5) -150_ | _+138_ | _(O: 8) -115_ |
| Chicago White Sox | _(-1.5) +130_ | _-152_ | _(U: 8) -105_ |
| Tuesday,<br> Aug. 11,<br> 09:50 pm | Houston Astros at | _(-1.5) -114_ | _-184_ | _(O: 8) -109_ |
| San Francisco Giants | _(+1.5) -106_ | _+166_ | _(U: 8) -111_ |
| Tuesday,<br> Aug. 11,<br> 10:15 pm | Kansas City Royals at | _(+1.5) -104_ | _+225_ | _(O: 8) -123_ |
| Los Angeles Dodgers | _(-1.5) -116_ | _-252_ | _(U: 8) +103_ |

Quick

Links

- LIVE ODDS
- [Boxing](https://www.sportsbet.com/live-odds/boxing.html?id=Matchups)
- [College Football](https://www.sportsbet.com/live-odds/football.html?id=College%20Football)
- [College Basketball](https://www.sportsbet.com/live-odds/basketball.html?id=CollegeBB)
- [Golf](https://www.sportsbet.com/live-odds/golf.html?id=Golf%20-%20Futures)
- [MLS](https://www.sportsbet.com/live-odds/soccer.html?id=MLS)
- [MMA](https://www.sportsbet.com/live-odds/mma.html?id=Matchups)
- [NBA](https://www.sportsbet.com/live-odds/basketball.html?id=NBA)
- [NFL](https://www.sportsbet.com/live-odds/football.html?id=NFL)
- [NHL](https://www.sportsbet.com/live-odds/hockey.html?id=NHL)
- [Politics](https://www.sportsbet.com/live-odds/politics.html?id=Politics%20Futures)
- [Tennis](https://www.sportsbet.com/live-odds/tennis.html?id=ATP)
- BET TYPES
- [Point Spreads](https://www.sportsbet.com/sports-bet-types/point-spread-bet.html)
- [Money Lines](https://www.sportsbet.com/sports-bet-types/money-lines-bet.html)
- [Totals](https://www.sportsbet.com/sports-bet-types/totals-bet.html)
- [European Prices](https://www.sportsbet.com/sports-bet-types/european-prices-bet.html)
- [Quarter Lines](https://www.sportsbet.com/sports-bet-types/quarter-lines-bet.html)
- [Half-Time Lines](https://www.sportsbet.com/sports-bet-types/half-time-lines-bet.html)
- [Parlays](https://www.sportsbet.com/sports-bet-types/parlay-bet.html)
- [Progressive Parlays](https://www.sportsbet.com/sports-bet-types/progressive-parlay-bet.html)
- [Teasers](https://www.sportsbet.com/sports-bet-types/teaser-bet.html)
- [If Bets](https://www.sportsbet.com/sports-bet-types/if-bet.html)
- [Futures](https://www.sportsbet.com/sports-bet-types/futures-propositions-bet.html)
- [Propositions](https://www.sportsbet.com/sports-bet-types/futures-propositions-bet.html)
- LEARN TO BET
- [Auto Racing](https://www.sportsbet.com/sportsbook/auto-racing-bet.html)
- [Baseball](https://www.sportsbet.com/sportsbook/baseball-bet.html)
- [Basketball](https://www.sportsbet.com/sportsbook/basketball-bet.html)
- [Boxing](https://www.sportsbet.com/sportsbook/bet-on-boxing.html)
- [Football](https://www.sportsbet.com/sportsbook/football-bet.html)
- [Golf](https://www.sportsbet.com/sportsbook/golf-bet.html)
- [Hockey](https://www.sportsbet.com/sportsbook/hockey-bet.html)
- [Soccer](https://www.sportsbet.com/sportsbook/soccer-bet.html)
- [Tennis](https://www.sportsbet.com/sportsbook/tennis-bet.html)
- [Payout Calculator](https://www.sportsbet.com/live-odds/baseball.html?id=MLB#)

Fantasy Sports 970x90

GET INTO THE

FANTASY

SPORTS

ACTION

18+ \| #ad

SportsBet®

your source for betting information

Twitter Widget Iframe"""

# TODO: Function to parse for tables via REGEX HTML/MD format pattern -> Returns tables in list[str, str, ...] e.g. [table1, table2, table3, ...]

<>:100: SyntaxWarning: "\|" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\|"? A raw string is also an option.
<>:100: SyntaxWarning: "\|" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\|"? A raw string is also an option.
/var/folders/15/rhzv7t4942x20vymgpp8qt2r0000gn/T/ipykernel_75832/765826708.py:100: SyntaxWarning: "\|" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\|"? A raw string is also an option.
  18+ \| #ad

In [3]:
crawler_tables_found = """| DATE | MATCHUP | SPREAD | MONEY | TOTAL |
| --- | --- | --- | --- | --- |
| Tuesday,<br> Aug. 11,<br> 06:45 pm | Pittsburgh Pirates at | _(-1.5) +146_ | _-119_ | _(O: 7) -113_ |
| Miami Marlins | _(+1.5) -166_ | _+108_ | _(U: 7) -107_ |
| Tuesday,<br> Aug. 11,<br> 06:50 pm | Chicago Cubs at | _(-1.5) -105_ | _-163_ | _(O: 9) -104_ |
| Washington Nationals | _(+1.5) -115_ | _+147_ | _(U: 9) -116_ |
| Tuesday,<br> Aug. 11,<br> 07:20 pm | New York Mets at | _(+1.5) -185_ | _+113_ | _(O: 8) -125_ |
| Atlanta Braves | _(-1.5) +161_ | _-125_ | _(U: 8) +105_ |
| Tuesday,<br> Aug. 11,<br> 07:50 pm | Philadelphia Phillies at | _(-1.5) +103_ | _-160_ | _(O: 8) -115_ |
| St. Louis Cardinals | _(+1.5) -123_ | _+145_ | _(U: 8) -105_ |
| Tuesday,<br> Aug. 11,<br> 09:45 pm | Colorado Rockies at | _(+1.5) -133_ | _+157_ | _(O: 9) -125_ |
| Arizona Diamondbacks | _(-1.5) +113_ | _-174_ | _(U: 9) +105_ |
| Tuesday,<br> Aug. 11,<br> 09:45 pm | Milwaukee Brewers at | _(-1.5) +125_ | _-138_ | _(O: 8) +105_ |
| San Diego Padres | _(+1.5) -145_ | _+125_ | _(U: 8) -125_ |
| Tuesday,<br> Aug. 11,<br> 06:45 pm | Cleveland Guardians at | _(+1.5) -190_ | _+113_ | _(O: 8.5) -110_ |
| Detroit Tigers | _(-1.5) +165_ | _-125_ | _(U: 8.5) -110_ |
| Tuesday,<br> Aug. 11,<br> 07:10 pm | Seattle Mariners at | _(+1.5) -185_ | _+113_ | _(O: 8.5) +105_ |
| New York Yankees | _(-1.5) +161_ | _-125_ | _(U: 8.5) -125_ |
| Tuesday,<br> Aug. 11,<br> 07:12 pm | Boston Red Sox at | _(+1.5) -167_ | _+127_ | _(O: 7.5) +108_ |
| Toronto Blue Jays | _(-1.5) +147_ | _-140_ | _(U: 7.5) -128_ |
| Tuesday,<br> Aug. 11,<br> 07:45 pm | Baltimore Orioles at | _(+1.5) -195_ | _+104_ | _(O: 9.5) -105_ |
| Minnesota Twins | _(-1.5) +170_ | _-115_ | _(U: 9.5) -115_ |
| Tuesday,<br> Aug. 11,<br> 09:43 pm | Texas Rangers at | _(-1.5) +115_ | _-138_ | _(O: 9) -118_ |
| Los Angeles Angels | _(+1.5) -135_ | _+125_ | _(U: 9) -102_ |
| Tuesday,<br> Aug. 11,<br> 09:45 pm | Tampa Bay Rays at | _(-1.5) -102_ | _-158_ | _(O: 9.5) -126_ |
| Athletics | _(+1.5) -118_ | _+143_ | _(U: 9.5) +106_ |
| Tuesday,<br> Aug. 11,<br> 07:45 pm | Cincinnati Reds at | _(+1.5) -150_ | _+138_ | _(O: 8) -115_ |
| Chicago White Sox | _(-1.5) +130_ | _-152_ | _(U: 8) -105_ |
| Tuesday,<br> Aug. 11,<br> 09:50 pm | Houston Astros at | _(-1.5) -114_ | _-184_ | _(O: 8) -109_ |
| San Francisco Giants | _(+1.5) -106_ | _+166_ | _(U: 8) -111_ |
| Tuesday,<br> Aug. 11,<br> 10:15 pm | Kansas City Royals at | _(+1.5) -104_ | _+225_ | _(O: 8) -123_ |
| Los Angeles Dodgers | _(-1.5) -116_ | _-252_ | _(U: 8) +103_ |"""

## Method 1

In [41]:
import pandas as pd
from io import StringIO

df = (
    pd.read_csv(StringIO(crawler_tables_found), sep="|", skipinitialspace=True)
    # .dropna(axis=2, how="all")  # drop empty edge columns
    .rename(columns=lambda c: c.strip())  # clean header names
    .iloc[1:]  # drop the |---| divider row
    .reset_index(drop=True)
)

df

,Unnamed: 0,DATE,MATCHUP,SPREAD,MONEY,TOTAL,Unnamed: 6
0,NaN,"Tuesday,<br> Aug. 11,<br> 06:45 pm",Pittsburgh Pirates at,_(-1.5) +146_,_-119_,_(O: 7) -113_,NaN
1,NaN,Miami Marlins,_(+1.5) -166_,_+108_,_(U: 7) -107_,NaN,NaN
2,NaN,"Tuesday,<br> Aug. 11,<br> 06:50 pm",Chicago Cubs at,_(-1.5) -105_,_-163_,_(O: 9) -104_,NaN
3,NaN,Washington Nationals,_(+1.5) -115_,_+147_,_(U: 9) -116_,NaN,NaN
4,NaN,"Tuesday,<br> Aug. 11,<br> 07:20 pm",New York Mets at,_(+1.5) -185_,_+113_,_(O: 8) -125_,NaN
5,NaN,Atlanta Braves,_(-1.5) +161_,_-125_,_(U: 8) +105_,NaN,NaN
6,NaN,"Tuesday,<br> Aug. 11,<br> 07:50 pm",Philadelphia Phillies at,_(-1.5) +103_,_-160_,_(O: 8) -115_,NaN
7,NaN,St. Louis Cardinals,_(+1.5) -123_,_+145_,_(U: 8) -105_,NaN,NaN
8,NaN,"Tuesday,<br> Aug. 11,<br> 09:45 pm",Colorado Rockies at,_(+1.5) -133_,_+157_,_(O: 9) -125_,NaN
9,NaN,Arizona Diamondbacks,_(-1.5) +113_,_-174_,_(U: 9) +105_,NaN,NaN
10,NaN,"Tuesday,<br> Aug. 11,<br> 09:45 pm",Milwaukee Brewers at,_(-1.5) +125_,_-138_,_(O: 8) +105_,NaN
11,NaN,San Diego Padres,_(+1.5) -145_,_+125_,_(U: 8) -125_,NaN,NaN
12,NaN,"Tuesday,<br> Aug. 11,<br> 06:45 pm",Cleveland Guardians at,_(+1.5) -190_,_+113_,_(O: 8.5) -110_,NaN
13,NaN,Detroit Tigers,_(-1.5) +165_,_-125_,_(U: 8.5) -110_,NaN,NaN
14,NaN,"Tuesday,<br> Aug. 11,<br> 07:10 pm",Seattle Mariners at,_(+1.5) -185_,_+113_,_(O: 8.5) +105_,NaN
15,NaN,New York Yankees,_(-1.5) +161_,_-125_,_(U: 8.5) -125_,NaN,NaN
16,NaN,"Tuesday,<br> Aug. 11,<br> 07:12 pm",Boston Red Sox at,_(+1.5) -167_,_+127_,_(O: 7.5) +108_,NaN
17,NaN,Toronto Blue Jays,_(-1.5) +147_,_-140_,_(U: 7.5) -128_,NaN,NaN
18,NaN,"Tuesday,<br> Aug. 11,<br> 07:45 pm",Baltimore Orioles at,_(+1.5) -195_,_+104_,_(O: 9.5) -105_,NaN
19,NaN,Minnesota Twins,_(-1.5) +170_,_-115_,_(U: 9.5) -115_,NaN,NaN
20,NaN,"Tuesday,<br> Aug. 11,<br> 09:43 pm",Texas Rangers at,_(-1.5) +115_,_-138_,_(O: 9) -118_,NaN
21,NaN,Los Angeles Angels,_(+1.5) -135_,_+125_,_(U: 9) -102_,NaN,NaN
22,NaN,"Tuesday,<br> Aug. 11,<br> 09:45 pm",Tampa Bay Rays at,_(-1.5) -102_,_-158_,_(O: 9.5) -126_,NaN
23,NaN,Athletics,_(+1.5) -118_,_+143_,_(U: 9.5) +106_,NaN,NaN
24,NaN,"Tuesday,<br> Aug. 11,<br> 07:45 pm",Cincinnati Reds at,_(+1.5) -150_,_+138_,_(O: 8) -115_,NaN
25,NaN,Chicago White Sox,_(-1.5) +130_,_-152_,_(U: 8) -105_,NaN,NaN
26,NaN,"Tuesday,<br> Aug. 11,<br> 09:50 pm",Houston Astros at,_(-1.5) -114_,_-184_,_(O: 8) -109_,NaN
27,NaN,San Francisco Giants,_(+1.5) -106_,_+166_,_(U: 8) -111_,NaN,NaN
28,NaN,"Tuesday,<br> Aug. 11,<br> 10:15 pm",Kansas City Royals at,_(+1.5) -104_,_+225_,_(O: 8) -123_,NaN
29,NaN,Los Angeles Dodgers,_(-1.5) -116_,_-252_,_(U: 8) +103_,NaN,NaN

## Method 2

In [47]:
import markdown  # pip install markdown

html = markdown.markdown(
    crawler_tables_found, extensions=["tables"], output_format="html", tab_length=4
)
dm = pd.read_html(StringIO(html))
dm

[                            DATE                   MATCHUP       SPREAD  \
 0   Tuesday,  Aug. 11,  06:45 pm     Pittsburgh Pirates at  (-1.5) +146
 1                  Miami Marlins               (+1.5) -166         +108
 2   Tuesday,  Aug. 11,  06:50 pm           Chicago Cubs at  (-1.5) -105
 3           Washington Nationals               (+1.5) -115         +147
 4   Tuesday,  Aug. 11,  07:20 pm          New York Mets at  (+1.5) -185
 5                 Atlanta Braves               (-1.5) +161         -125
 6   Tuesday,  Aug. 11,  07:50 pm  Philadelphia Phillies at  (-1.5) +103
 7            St. Louis Cardinals               (+1.5) -123         +145
 8   Tuesday,  Aug. 11,  09:45 pm       Colorado Rockies at  (+1.5) -133
 9           Arizona Diamondbacks               (-1.5) +113         -174
 10  Tuesday,  Aug. 11,  09:45 pm      Milwaukee Brewers at  (-1.5) +125
 11              San Diego Padres               (+1.5) -145         +125
 12  Tuesday,  Aug. 11,  06:45 pm    Cleveland Guardians at  (+1.5) -190
 13                Detroit Tigers               (-1.5) +165         -125
 14  Tuesday,  Aug. 11,  07:10 pm       Seattle Mariners at  (+1.5) -185
 15              New York Yankees               (-1.5) +161         -125
 16  Tuesday,  Aug. 11,  07:12 pm         Boston Red Sox at  (+1.5) -167
 17             Toronto Blue Jays               (-1.5) +147         -140
 18  Tuesday,  Aug. 11,  07:45 pm      Baltimore Orioles at  (+1.5) -195
 19               Minnesota Twins               (-1.5) +170         -115
 20  Tuesday,  Aug. 11,  09:43 pm          Texas Rangers at  (-1.5) +115
 21            Los Angeles Angels               (+1.5) -135         +125
 22  Tuesday,  Aug. 11,  09:45 pm         Tampa Bay Rays at  (-1.5) -102
 23                     Athletics               (+1.5) -118         +143
 24  Tuesday,  Aug. 11,  07:45 pm        Cincinnati Reds at  (+1.5) -150
 25             Chicago White Sox               (-1.5) +130         -152
 26  Tuesday,  Aug. 11,  09:50 pm         Houston Astros at  (-1.5) -114
 27          San Francisco Giants               (+1.5) -106         +166
 28  Tuesday,  Aug. 11,  10:15 pm     Kansas City Royals at  (+1.5) -104
 29           Los Angeles Dodgers               (-1.5) -116         -252

             MONEY          TOTAL
 0            -119    (O: 7) -113
 1     (U: 7) -107            NaN
 2            -163    (O: 9) -104
 3     (U: 9) -116            NaN
 4            +113    (O: 8) -125
 5     (U: 8) +105            NaN
 6            -160    (O: 8) -115
 7     (U: 8) -105            NaN
 8            +157    (O: 9) -125
 9     (U: 9) +105            NaN
 10           -138    (O: 8) +105
 11    (U: 8) -125            NaN
 12           +113  (O: 8.5) -110
 13  (U: 8.5) -110            NaN
 14           +113  (O: 8.5) +105
 15  (U: 8.5) -125            NaN
 16           +127  (O: 7.5) +108
 17  (U: 7.5) -128            NaN
 18           +104  (O: 9.5) -105
 19  (U: 9.5) -115            NaN
 20           -138    (O: 9) -118
 21    (U: 9) -102            NaN
 22           -158  (O: 9.5) -126
 23  (U: 9.5) +106            NaN
 24           +138    (O: 8) -115
 25    (U: 8) -105            NaN
 26           -184    (O: 8) -109
 27    (U: 8) -111            NaN
 28           +225    (O: 8) -123
 29    (U: 8) +103            NaN  ]

In [48]:
dm[0]

,DATE,MATCHUP,SPREAD,MONEY,TOTAL
0,"Tuesday, Aug. 11, 06:45 pm",Pittsburgh Pirates at,(-1.5) +146,-119,(O: 7) -113
1,Miami Marlins,(+1.5) -166,+108,(U: 7) -107,NaN
2,"Tuesday, Aug. 11, 06:50 pm",Chicago Cubs at,(-1.5) -105,-163,(O: 9) -104
3,Washington Nationals,(+1.5) -115,+147,(U: 9) -116,NaN
4,"Tuesday, Aug. 11, 07:20 pm",New York Mets at,(+1.5) -185,+113,(O: 8) -125
5,Atlanta Braves,(-1.5) +161,-125,(U: 8) +105,NaN
6,"Tuesday, Aug. 11, 07:50 pm",Philadelphia Phillies at,(-1.5) +103,-160,(O: 8) -115
7,St. Louis Cardinals,(+1.5) -123,+145,(U: 8) -105,NaN
8,"Tuesday, Aug. 11, 09:45 pm",Colorado Rockies at,(+1.5) -133,+157,(O: 9) -125
9,Arizona Diamondbacks,(-1.5) +113,-174,(U: 9) +105,NaN
10,"Tuesday, Aug. 11, 09:45 pm",Milwaukee Brewers at,(-1.5) +125,-138,(O: 8) +105
11,San Diego Padres,(+1.5) -145,+125,(U: 8) -125,NaN
12,"Tuesday, Aug. 11, 06:45 pm",Cleveland Guardians at,(+1.5) -190,+113,(O: 8.5) -110
13,Detroit Tigers,(-1.5) +165,-125,(U: 8.5) -110,NaN
14,"Tuesday, Aug. 11, 07:10 pm",Seattle Mariners at,(+1.5) -185,+113,(O: 8.5) +105
15,New York Yankees,(-1.5) +161,-125,(U: 8.5) -125,NaN
16,"Tuesday, Aug. 11, 07:12 pm",Boston Red Sox at,(+1.5) -167,+127,(O: 7.5) +108
17,Toronto Blue Jays,(-1.5) +147,-140,(U: 7.5) -128,NaN
18,"Tuesday, Aug. 11, 07:45 pm",Baltimore Orioles at,(+1.5) -195,+104,(O: 9.5) -105
19,Minnesota Twins,(-1.5) +170,-115,(U: 9.5) -115,NaN
20,"Tuesday, Aug. 11, 09:43 pm",Texas Rangers at,(-1.5) +115,-138,(O: 9) -118
21,Los Angeles Angels,(+1.5) -135,+125,(U: 9) -102,NaN
22,"Tuesday, Aug. 11, 09:45 pm",Tampa Bay Rays at,(-1.5) -102,-158,(O: 9.5) -126
23,Athletics,(+1.5) -118,+143,(U: 9.5) +106,NaN
24,"Tuesday, Aug. 11, 07:45 pm",Cincinnati Reds at,(+1.5) -150,+138,(O: 8) -115
25,Chicago White Sox,(-1.5) +130,-152,(U: 8) -105,NaN
26,"Tuesday, Aug. 11, 09:50 pm",Houston Astros at,(-1.5) -114,-184,(O: 8) -109
27,San Francisco Giants,(+1.5) -106,+166,(U: 8) -111,NaN
28,"Tuesday, Aug. 11, 10:15 pm",Kansas City Royals at,(+1.5) -104,+225,(O: 8) -123
29,Los Angeles Dodgers,(-1.5) -116,-252,(U: 8) +103,NaN

## Method 3

Uses the same HTML output from Method 2.

In [49]:
import pandas as pd
from io import StringIO

df = pd.read_html(StringIO(html))[0]

away = df.iloc[::2].reset_index(drop=True)
home = df.iloc[1::2].reset_index(drop=True)


# Split "(-1.5) +146" or "(O: 7) -113" into line and odds
def line_odds(s):
    return s.str.extract(r"\(?[OU:\s]*([+-]?\d+\.?\d*)\)?\s*([+-]\d+)").astype(float)


games = pd.DataFrame(
    {
        "date": pd.to_datetime(
            away["DATE"]
            .str.replace(r"^\w+,\s*", "", regex=True)  # drop weekday
            .str.replace(r"\s+", " ", regex=True)  # collapse double spaces
            .str.strip()
            + " 2026",
            format="%b. %d, %I:%M %p %Y",
        ),
        "away_team": away["MATCHUP"].str.removesuffix(" at").str.strip(),
        "home_team": home["DATE"],
        "away_ml": away["MONEY"].astype(int),
        "home_ml": home["SPREAD"].astype(int),
    }
)

games[["away_spread", "away_spread_odds"]] = line_odds(away["SPREAD"]).values
games[["home_spread", "home_spread_odds"]] = line_odds(home["MATCHUP"]).values
games[["total", "over_odds"]] = line_odds(away["TOTAL"]).values
games["under_odds"] = line_odds(home["MONEY"])[1].values

In [50]:
games

,date,away_team,home_team,away_ml,home_ml,away_spread,away_spread_odds,home_spread,home_spread_odds,total,over_odds,under_odds
0,2026-08-11 18:45:00,Pittsburgh Pirates,Miami Marlins,-119,108,-1.5,146.0,1.5,-166.0,7.0,-113.0,-107.0
1,2026-08-11 18:50:00,Chicago Cubs,Washington Nationals,-163,147,-1.5,-105.0,1.5,-115.0,9.0,-104.0,-116.0
2,2026-08-11 19:20:00,New York Mets,Atlanta Braves,113,-125,1.5,-185.0,-1.5,161.0,8.0,-125.0,105.0
3,2026-08-11 19:50:00,Philadelphia Phillies,St. Louis Cardinals,-160,145,-1.5,103.0,1.5,-123.0,8.0,-115.0,-105.0
4,2026-08-11 21:45:00,Colorado Rockies,Arizona Diamondbacks,157,-174,1.5,-133.0,-1.5,113.0,9.0,-125.0,105.0
5,2026-08-11 21:45:00,Milwaukee Brewers,San Diego Padres,-138,125,-1.5,125.0,1.5,-145.0,8.0,105.0,-125.0
6,2026-08-11 18:45:00,Cleveland Guardians,Detroit Tigers,113,-125,1.5,-190.0,-1.5,165.0,8.5,-110.0,-110.0
7,2026-08-11 19:10:00,Seattle Mariners,New York Yankees,113,-125,1.5,-185.0,-1.5,161.0,8.5,105.0,-125.0
8,2026-08-11 19:12:00,Boston Red Sox,Toronto Blue Jays,127,-140,1.5,-167.0,-1.5,147.0,7.5,108.0,-128.0
9,2026-08-11 19:45:00,Baltimore Orioles,Minnesota Twins,104,-115,1.5,-195.0,-1.5,170.0,9.5,-105.0,-115.0
10,2026-08-11 21:43:00,Texas Rangers,Los Angeles Angels,-138,125,-1.5,115.0,1.5,-135.0,9.0,-118.0,-102.0
11,2026-08-11 21:45:00,Tampa Bay Rays,Athletics,-158,143,-1.5,-102.0,1.5,-118.0,9.5,-126.0,106.0
12,2026-08-11 19:45:00,Cincinnati Reds,Chicago White Sox,138,-152,1.5,-150.0,-1.5,130.0,8.0,-115.0,-105.0
13,2026-08-11 21:50:00,Houston Astros,San Francisco Giants,-184,166,-1.5,-114.0,1.5,-106.0,8.0,-109.0,-111.0
14,2026-08-11 22:15:00,Kansas City Royals,Los Angeles Dodgers,225,-252,1.5,-104.0,-1.5,-116.0,8.0,-123.0,103.0